sensors:
 - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
   point_cloud_topic: /point_cloud_for_octomap
   max_range: 4.0
   padding_offset: 0.1
   padding_scale: 1.0
   frame_subsample: 1
   point_subsample: 1
   filtered_cloud_topic: filtered_cloud
